[workspace]
package.version = "0.1.4"
members = [
  "pac/ra6m3",
  "ra-fsp-rs",
  "ra-fsp-sys",
  "update-pacs",
]
exclude = []
resolver = "2"

[workspace.dependencies]
ra-fsp-sys = { version = "0.1.4" }
ra6m3-pac = { version = "0.1.4", package = "ra6m3-fsp-pac"  }
