[workspace]
package.version = "0.1.2"
members = [
  "pac/ra6m3",
  "ra-fsp-rs",
  "ra-fsp-sys",
  "update-pacs",
]
exclude = [
]
resolver = "2"

[workspace.dependencies]
ra-fsp-sys = { path = "./ra-fsp-sys" }
