[workspace]
package.version = "0.1.6"
members = [
  "pac/ra4m1",
  "pac/ra6m3",
  "ra-fsp-rs",
  "ra-fsp-sys",
  "update-pacs",
]
exclude = []
resolver = "2"

[workspace.dependencies]
ra-fsp-sys = { version = "0.1.5", default-features = false }
ra6m3-pac = { version = "0.1.5", package = "ra6m3-fsp-pac", default-features = false }
ra4m1-pac = { version = "0.1.5", package = "ra4m1-fsp-pac", default-features = false }
