/*!Peripheral access API for R7FA4M1AB microcontrollers (generated using svd2rust v0.36.1 (23464b3 2025-06-27))

You can find an overview of the generated API [here].

API features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.

[here]: https://docs.rs/svd2rust/0.36.1/svd2rust/#peripheral-api
[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased
[repository]: https://github.com/rust-embedded/svd2rust*/
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
///Number available in the NVIC for configuring priority
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
///Common register and bit access and modify traits
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn IEL0();
    fn IEL1();
    fn IEL2();
    fn IEL3();
    fn IEL4();
    fn IEL5();
    fn IEL6();
    fn IEL7();
    fn IEL8();
    fn IEL9();
    fn IEL10();
    fn IEL11();
    fn IEL12();
    fn IEL13();
    fn IEL14();
    fn IEL15();
    fn IEL16();
    fn IEL17();
    fn IEL18();
    fn IEL19();
    fn IEL20();
    fn IEL21();
    fn IEL22();
    fn IEL23();
    fn IEL24();
    fn IEL25();
    fn IEL26();
    fn IEL27();
    fn IEL28();
    fn IEL29();
    fn IEL30();
    fn IEL31();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[cfg_attr(feature = "fsp", link_section = ".application_vectors")]
#[cfg_attr(
    feature = "cortex-m-rt-device",
    link_section = ".vector_table.interrupts"
)]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 32] = [
    Vector { _handler: IEL0 },
    Vector { _handler: IEL1 },
    Vector { _handler: IEL2 },
    Vector { _handler: IEL3 },
    Vector { _handler: IEL4 },
    Vector { _handler: IEL5 },
    Vector { _handler: IEL6 },
    Vector { _handler: IEL7 },
    Vector { _handler: IEL8 },
    Vector { _handler: IEL9 },
    Vector { _handler: IEL10 },
    Vector { _handler: IEL11 },
    Vector { _handler: IEL12 },
    Vector { _handler: IEL13 },
    Vector { _handler: IEL14 },
    Vector { _handler: IEL15 },
    Vector { _handler: IEL16 },
    Vector { _handler: IEL17 },
    Vector { _handler: IEL18 },
    Vector { _handler: IEL19 },
    Vector { _handler: IEL20 },
    Vector { _handler: IEL21 },
    Vector { _handler: IEL22 },
    Vector { _handler: IEL23 },
    Vector { _handler: IEL24 },
    Vector { _handler: IEL25 },
    Vector { _handler: IEL26 },
    Vector { _handler: IEL27 },
    Vector { _handler: IEL28 },
    Vector { _handler: IEL29 },
    Vector { _handler: IEL30 },
    Vector { _handler: IEL31 },
];
///Enumeration of all the interrupts.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    ///0 - ICU Interrupt 0
    IEL0 = 0,
    ///1 - ICU Interrupt 1
    IEL1 = 1,
    ///2 - ICU Interrupt 2
    IEL2 = 2,
    ///3 - ICU Interrupt 3
    IEL3 = 3,
    ///4 - ICU Interrupt 4
    IEL4 = 4,
    ///5 - ICU Interrupt 5
    IEL5 = 5,
    ///6 - ICU Interrupt 6
    IEL6 = 6,
    ///7 - ICU Interrupt 7
    IEL7 = 7,
    ///8 - ICU Interrupt 8
    IEL8 = 8,
    ///9 - ICU Interrupt 9
    IEL9 = 9,
    ///10 - ICU Interrupt 10
    IEL10 = 10,
    ///11 - ICU Interrupt 11
    IEL11 = 11,
    ///12 - ICU Interrupt 12
    IEL12 = 12,
    ///13 - ICU Interrupt 13
    IEL13 = 13,
    ///14 - ICU Interrupt 14
    IEL14 = 14,
    ///15 - ICU Interrupt 15
    IEL15 = 15,
    ///16 - ICU Interrupt 16
    IEL16 = 16,
    ///17 - ICU Interrupt 17
    IEL17 = 17,
    ///18 - ICU Interrupt 18
    IEL18 = 18,
    ///19 - ICU Interrupt 19
    IEL19 = 19,
    ///20 - ICU Interrupt 20
    IEL20 = 20,
    ///21 - ICU Interrupt 21
    IEL21 = 21,
    ///22 - ICU Interrupt 22
    IEL22 = 22,
    ///23 - ICU Interrupt 23
    IEL23 = 23,
    ///24 - ICU Interrupt 24
    IEL24 = 24,
    ///25 - ICU Interrupt 25
    IEL25 = 25,
    ///26 - ICU Interrupt 26
    IEL26 = 26,
    ///27 - ICU Interrupt 27
    IEL27 = 27,
    ///28 - ICU Interrupt 28
    IEL28 = 28,
    ///29 - ICU Interrupt 29
    IEL29 = 29,
    ///30 - ICU Interrupt 30
    IEL30 = 30,
    ///31 - ICU Interrupt 31
    IEL31 = 31,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
///System Control
pub type SYSTEM = crate::Periph<system::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for SYSTEM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SYSTEM").finish()
    }
}
///System Control
pub mod system;
///BUS Control
pub type BUS = crate::Periph<bus::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for BUS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BUS").finish()
    }
}
///BUS Control
pub mod bus;
///Clock Frequency Accuracy Measurement Circuit
pub type CAC = crate::Periph<cac::RegisterBlock, 0x4004_4600>;
impl core::fmt::Debug for CAC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CAC").finish()
    }
}
///Clock Frequency Accuracy Measurement Circuit
pub mod cac;
///CAN0 Module
pub type CAN0 = crate::Periph<can0::RegisterBlock, 0x4005_0000>;
impl core::fmt::Debug for CAN0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CAN0").finish()
    }
}
///CAN0 Module
pub mod can0;
///Debug Function
pub type DBG = crate::Periph<dbg::RegisterBlock, 0x4001_b000>;
impl core::fmt::Debug for DBG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DBG").finish()
    }
}
///Debug Function
pub mod dbg;
///CRC Calculator
pub type CRC = crate::Periph<crc::RegisterBlock, 0x4007_4000>;
impl core::fmt::Debug for CRC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CRC").finish()
    }
}
///CRC Calculator
pub mod crc;
///Capacitive Touch Sensing Unit
pub type CTSU = crate::Periph<ctsu::RegisterBlock, 0x4008_1000>;
impl core::fmt::Debug for CTSU {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CTSU").finish()
    }
}
///Capacitive Touch Sensing Unit
pub mod ctsu;
///12-bit D/A converter
pub type DAC12 = crate::Periph<dac12::RegisterBlock, 0x4005_e000>;
impl core::fmt::Debug for DAC12 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DAC12").finish()
    }
}
///12-bit D/A converter
pub mod dac12;
///8-bit D/A converter
pub type DAC8 = crate::Periph<dac8::RegisterBlock, 0x4009_e000>;
impl core::fmt::Debug for DAC8 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DAC8").finish()
    }
}
///8-bit D/A converter
pub mod dac8;
///Direct memory access controller 0
pub type DMAC0 = crate::Periph<dmac0::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for DMAC0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMAC0").finish()
    }
}
///Direct memory access controller 0
pub mod dmac0;
///Direct memory access controller 1
pub type DMAC1 = crate::Periph<dmac0::RegisterBlock, 0x4000_5040>;
impl core::fmt::Debug for DMAC1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMAC1").finish()
    }
}
///Direct memory access controller 1
pub use self::dmac0 as dmac1;
///Direct memory access controller 2
pub type DMAC2 = crate::Periph<dmac0::RegisterBlock, 0x4000_5080>;
impl core::fmt::Debug for DMAC2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMAC2").finish()
    }
}
///Direct memory access controller 2
pub use self::dmac0 as dmac2;
///Direct memory access controller 3
pub type DMAC3 = crate::Periph<dmac0::RegisterBlock, 0x4000_50c0>;
impl core::fmt::Debug for DMAC3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMAC3").finish()
    }
}
///Direct memory access controller 3
pub use self::dmac0 as dmac3;
///DMAC Module Activation
pub type DMA = crate::Periph<dma::RegisterBlock, 0x4000_5200>;
impl core::fmt::Debug for DMA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DMA").finish()
    }
}
///DMAC Module Activation
pub mod dma;
///Data Operation Circuit
pub type DOC = crate::Periph<doc::RegisterBlock, 0x4005_4100>;
impl core::fmt::Debug for DOC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DOC").finish()
    }
}
///Data Operation Circuit
pub mod doc;
///Data Transfer Controller
pub type DTC = crate::Periph<dtc::RegisterBlock, 0x4000_5400>;
impl core::fmt::Debug for DTC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DTC").finish()
    }
}
///Data Transfer Controller
pub mod dtc;
///Event Link Controller
pub type ELC = crate::Periph<elc::RegisterBlock, 0x4004_1000>;
impl core::fmt::Debug for ELC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ELC").finish()
    }
}
///Event Link Controller
pub mod elc;
///Flash Cache
pub type FCACHE = crate::Periph<fcache::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for FCACHE {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FCACHE").finish()
    }
}
///Flash Cache
pub mod fcache;
///Port 0 Control Registers
pub type PORT0 = crate::Periph<port0::RegisterBlock, 0x4004_0000>;
impl core::fmt::Debug for PORT0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PORT0").finish()
    }
}
///Port 0 Control Registers
pub mod port0;
///Port 1 Control Registers
pub type PORT1 = crate::Periph<port1::RegisterBlock, 0x4004_0020>;
impl core::fmt::Debug for PORT1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PORT1").finish()
    }
}
///Port 1 Control Registers
pub mod port1;
///Port 2 Control Registers
pub type PORT2 = crate::Periph<port1::RegisterBlock, 0x4004_0040>;
impl core::fmt::Debug for PORT2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PORT2").finish()
    }
}
///Port 2 Control Registers
pub use self::port1 as port2;
///Port 3 Control Registers
pub type PORT3 = crate::Periph<port1::RegisterBlock, 0x4004_0060>;
impl core::fmt::Debug for PORT3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PORT3").finish()
    }
}
///Port 3 Control Registers
pub use self::port1 as port3;
///Port 4 Control Registers
pub type PORT4 = crate::Periph<port1::RegisterBlock, 0x4004_0080>;
impl core::fmt::Debug for PORT4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PORT4").finish()
    }
}
///Port 4 Control Registers
pub use self::port1 as port4;
///Port 5 Control Registers
pub type PORT5 = crate::Periph<port0::RegisterBlock, 0x4004_00a0>;
impl core::fmt::Debug for PORT5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PORT5").finish()
    }
}
///Port 5 Control Registers
pub use self::port0 as port5;
///Port 6 Control Registers
pub type PORT6 = crate::Periph<port0::RegisterBlock, 0x4004_00c0>;
impl core::fmt::Debug for PORT6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PORT6").finish()
    }
}
///Port 6 Control Registers
pub use self::port0 as port6;
///Port 7 Control Registers
pub type PORT7 = crate::Periph<port0::RegisterBlock, 0x4004_00e0>;
impl core::fmt::Debug for PORT7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PORT7").finish()
    }
}
///Port 7 Control Registers
pub use self::port0 as port7;
///Port 8 Control Registers
pub type PORT8 = crate::Periph<port0::RegisterBlock, 0x4004_0100>;
impl core::fmt::Debug for PORT8 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PORT8").finish()
    }
}
///Port 8 Control Registers
pub use self::port0 as port8;
///Port 9 Control Registers
pub type PORT9 = crate::Periph<port0::RegisterBlock, 0x4004_0120>;
impl core::fmt::Debug for PORT9 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PORT9").finish()
    }
}
///Port 9 Control Registers
pub use self::port0 as port9;
///Pmn Pin Function Control Register
pub type PFS = crate::Periph<pfs::RegisterBlock, 0x4004_0800>;
impl core::fmt::Debug for PFS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PFS").finish()
    }
}
///Pmn Pin Function Control Register
pub mod pfs;
///Miscellaneous Port Control Register
pub type PMISC = crate::Periph<pmisc::RegisterBlock, 0x4004_0d00>;
impl core::fmt::Debug for PMISC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PMISC").finish()
    }
}
///Miscellaneous Port Control Register
pub mod pmisc;
///Interrupt Controller
pub type ICU = crate::Periph<icu::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for ICU {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ICU").finish()
    }
}
///Interrupt Controller
pub mod icu;
///Inter-Integrated Circuit 0
pub type IIC0 = crate::Periph<iic0::RegisterBlock, 0x4005_3000>;
impl core::fmt::Debug for IIC0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IIC0").finish()
    }
}
///Inter-Integrated Circuit 0
pub mod iic0;
///Inter-Integrated Circuit 1
pub type IIC1 = crate::Periph<iic1::RegisterBlock, 0x4005_3100>;
impl core::fmt::Debug for IIC1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IIC1").finish()
    }
}
///Inter-Integrated Circuit 1
pub mod iic1;
///Independent Watchdog Timer
pub type IWDT = crate::Periph<iwdt::RegisterBlock, 0x4004_4400>;
impl core::fmt::Debug for IWDT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IWDT").finish()
    }
}
///Independent Watchdog Timer
pub mod iwdt;
///Key Interrupt Function
pub type KINT = crate::Periph<kint::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for KINT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("KINT").finish()
    }
}
///Key Interrupt Function
pub mod kint;
///Module Stop Control B,C,D
pub type MSTP = crate::Periph<mstp::RegisterBlock, 0x4004_7000>;
impl core::fmt::Debug for MSTP {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MSTP").finish()
    }
}
///Module Stop Control B,C,D
pub mod mstp;
///Bus Master MPU
pub type MMPU = crate::Periph<mmpu::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for MMPU {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MMPU").finish()
    }
}
///Bus Master MPU
pub mod mmpu;
///Bus Slave MPU
pub type SMPU = crate::Periph<smpu::RegisterBlock, 0x4000_0c00>;
impl core::fmt::Debug for SMPU {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SMPU").finish()
    }
}
///Bus Slave MPU
pub mod smpu;
///CPU Stack Pointer Monitor
pub type SPMON = crate::Periph<spmon::RegisterBlock, 0x4000_0d00>;
impl core::fmt::Debug for SPMON {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPMON").finish()
    }
}
///CPU Stack Pointer Monitor
pub mod spmon;
///OperationalAmplifier
pub type OPAMP = crate::Periph<opamp::RegisterBlock, 0x4008_6000>;
impl core::fmt::Debug for OPAMP {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("OPAMP").finish()
    }
}
///OperationalAmplifier
pub mod opamp;
///Port Output Enable Module for GPT
pub type POEG = crate::Periph<poeg::RegisterBlock, 0x4004_2000>;
impl core::fmt::Debug for POEG {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("POEG").finish()
    }
}
///Port Output Enable Module for GPT
pub mod poeg;
///SRAM Control
pub type SRAM = crate::Periph<sram::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for SRAM {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SRAM").finish()
    }
}
///SRAM Control
pub mod sram;
///Realtime Clock
pub type RTC = crate::Periph<rtc::RegisterBlock, 0x4004_4000>;
impl core::fmt::Debug for RTC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RTC").finish()
    }
}
///Realtime Clock
pub mod rtc;
///Serial Communication Interface 0
pub type SCI0 = crate::Periph<sci0::RegisterBlock, 0x4007_0000>;
impl core::fmt::Debug for SCI0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SCI0").finish()
    }
}
///Serial Communication Interface 0
pub mod sci0;
///Serial Communication Interface 1
pub type SCI1 = crate::Periph<sci0::RegisterBlock, 0x4007_0020>;
impl core::fmt::Debug for SCI1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SCI1").finish()
    }
}
///Serial Communication Interface 1
pub use self::sci0 as sci1;
///Serial Communication Interface 2
pub type SCI2 = crate::Periph<sci2::RegisterBlock, 0x4007_0040>;
impl core::fmt::Debug for SCI2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SCI2").finish()
    }
}
///Serial Communication Interface 2
pub mod sci2;
///Serial Communication Interface 9
pub type SCI9 = crate::Periph<sci2::RegisterBlock, 0x4007_0120>;
impl core::fmt::Debug for SCI9 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SCI9").finish()
    }
}
///Serial Communication Interface 9
pub use self::sci2 as sci9;
///Segment LCD Controller/Driver
pub type SLCDC = crate::Periph<slcdc::RegisterBlock, 0x4008_2000>;
impl core::fmt::Debug for SLCDC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SLCDC").finish()
    }
}
///Segment LCD Controller/Driver
pub mod slcdc;
///Serial Peripheral Interface 0
pub type SPI0 = crate::Periph<spi0::RegisterBlock, 0x4007_2000>;
impl core::fmt::Debug for SPI0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI0").finish()
    }
}
///Serial Peripheral Interface 0
pub mod spi0;
///Serial Peripheral Interface 1
pub type SPI1 = crate::Periph<spi1::RegisterBlock, 0x4007_2100>;
impl core::fmt::Debug for SPI1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPI1").finish()
    }
}
///Serial Peripheral Interface 1
pub mod spi1;
///Serial Sound Interface Ver.2.0
pub type SSIE0 = crate::Periph<ssie0::RegisterBlock, 0x4004_e000>;
impl core::fmt::Debug for SSIE0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SSIE0").finish()
    }
}
///Serial Sound Interface Ver.2.0
pub mod ssie0;
///Temperature Sensor
pub type TSN = crate::Periph<tsn::RegisterBlock, 0x407e_c000>;
impl core::fmt::Debug for TSN {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TSN").finish()
    }
}
///Temperature Sensor
pub mod tsn;
///USB 2.0 FS Module
pub type USBFS = crate::Periph<usbfs::RegisterBlock, 0x4009_0000>;
impl core::fmt::Debug for USBFS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USBFS").finish()
    }
}
///USB 2.0 FS Module
pub mod usbfs;
///Watchdog Timer
pub type WDT = crate::Periph<wdt::RegisterBlock, 0x4004_4200>;
impl core::fmt::Debug for WDT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WDT").finish()
    }
}
///Watchdog Timer
pub mod wdt;
///Low-Power Analog Comparator
pub type ACMPLP = crate::Periph<acmplp::RegisterBlock, 0x4008_5e00>;
impl core::fmt::Debug for ACMPLP {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ACMPLP").finish()
    }
}
///Low-Power Analog Comparator
pub mod acmplp;
///14bit A/D Converter
pub type ADC140 = crate::Periph<adc140::RegisterBlock, 0x4005_c000>;
impl core::fmt::Debug for ADC140 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ADC140").finish()
    }
}
///14bit A/D Converter
pub mod adc140;
///Asynchronous General purpose Timer 0
pub type AGT0 = crate::Periph<agt0::RegisterBlock, 0x4008_4000>;
impl core::fmt::Debug for AGT0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("AGT0").finish()
    }
}
///Asynchronous General purpose Timer 0
pub mod agt0;
///Asynchronous General purpose Timer 1
pub type AGT1 = crate::Periph<agt0::RegisterBlock, 0x4008_4100>;
impl core::fmt::Debug for AGT1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("AGT1").finish()
    }
}
///Asynchronous General purpose Timer 1
pub use self::agt0 as agt1;
///General PWM Timer 0 (32-bit)
pub type GPT320 = crate::Periph<gpt320::RegisterBlock, 0x4007_8000>;
impl core::fmt::Debug for GPT320 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPT320").finish()
    }
}
///General PWM Timer 0 (32-bit)
pub mod gpt320;
///General PWM Timer 1 (32-bit)
pub type GPT321 = crate::Periph<gpt320::RegisterBlock, 0x4007_8100>;
impl core::fmt::Debug for GPT321 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPT321").finish()
    }
}
///General PWM Timer 1 (32-bit)
pub use self::gpt320 as gpt321;
///General PWM Timer 2 (16-bit)
pub type GPT162 = crate::Periph<gpt162::RegisterBlock, 0x4007_8200>;
impl core::fmt::Debug for GPT162 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPT162").finish()
    }
}
///General PWM Timer 2 (16-bit)
pub mod gpt162;
///General PWM Timer 3 (16-bit)
pub type GPT163 = crate::Periph<gpt162::RegisterBlock, 0x4007_8300>;
impl core::fmt::Debug for GPT163 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPT163").finish()
    }
}
///General PWM Timer 3 (16-bit)
pub use self::gpt162 as gpt163;
///General PWM Timer 4 (16-bit)
pub type GPT164 = crate::Periph<gpt162::RegisterBlock, 0x4007_8400>;
impl core::fmt::Debug for GPT164 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPT164").finish()
    }
}
///General PWM Timer 4 (16-bit)
pub use self::gpt162 as gpt164;
///General PWM Timer 5 (16-bit)
pub type GPT165 = crate::Periph<gpt162::RegisterBlock, 0x4007_8500>;
impl core::fmt::Debug for GPT165 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPT165").finish()
    }
}
///General PWM Timer 5 (16-bit)
pub use self::gpt162 as gpt165;
///General PWM Timer 6 (16-bit)
pub type GPT166 = crate::Periph<gpt162::RegisterBlock, 0x4007_8600>;
impl core::fmt::Debug for GPT166 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPT166").finish()
    }
}
///General PWM Timer 6 (16-bit)
pub use self::gpt162 as gpt166;
///General PWM Timer 7 (16-bit)
pub type GPT167 = crate::Periph<gpt162::RegisterBlock, 0x4007_8700>;
impl core::fmt::Debug for GPT167 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPT167").finish()
    }
}
///General PWM Timer 7 (16-bit)
pub use self::gpt162 as gpt167;
///Output Phase Switching Controller
pub type GPT_OPS = crate::Periph<gpt_ops::RegisterBlock, 0x4007_8ff0>;
impl core::fmt::Debug for GPT_OPS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GPT_OPS").finish()
    }
}
///Output Phase Switching Controller
pub mod gpt_ops;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
/// All the peripherals.
#[allow(non_snake_case)]
pub struct Peripherals {
    ///SYSTEM
    pub SYSTEM: SYSTEM,
    ///BUS
    pub BUS: BUS,
    ///CAC
    pub CAC: CAC,
    ///CAN0
    pub CAN0: CAN0,
    ///DBG
    pub DBG: DBG,
    ///CRC
    pub CRC: CRC,
    ///CTSU
    pub CTSU: CTSU,
    ///DAC12
    pub DAC12: DAC12,
    ///DAC8
    pub DAC8: DAC8,
    ///DMAC0
    pub DMAC0: DMAC0,
    ///DMAC1
    pub DMAC1: DMAC1,
    ///DMAC2
    pub DMAC2: DMAC2,
    ///DMAC3
    pub DMAC3: DMAC3,
    ///DMA
    pub DMA: DMA,
    ///DOC
    pub DOC: DOC,
    ///DTC
    pub DTC: DTC,
    ///ELC
    pub ELC: ELC,
    ///FCACHE
    pub FCACHE: FCACHE,
    ///PORT0
    pub PORT0: PORT0,
    ///PORT1
    pub PORT1: PORT1,
    ///PORT2
    pub PORT2: PORT2,
    ///PORT3
    pub PORT3: PORT3,
    ///PORT4
    pub PORT4: PORT4,
    ///PORT5
    pub PORT5: PORT5,
    ///PORT6
    pub PORT6: PORT6,
    ///PORT7
    pub PORT7: PORT7,
    ///PORT8
    pub PORT8: PORT8,
    ///PORT9
    pub PORT9: PORT9,
    ///PFS
    pub PFS: PFS,
    ///PMISC
    pub PMISC: PMISC,
    ///ICU
    pub ICU: ICU,
    ///IIC0
    pub IIC0: IIC0,
    ///IIC1
    pub IIC1: IIC1,
    ///IWDT
    pub IWDT: IWDT,
    ///KINT
    pub KINT: KINT,
    ///MSTP
    pub MSTP: MSTP,
    ///MMPU
    pub MMPU: MMPU,
    ///SMPU
    pub SMPU: SMPU,
    ///SPMON
    pub SPMON: SPMON,
    ///OPAMP
    pub OPAMP: OPAMP,
    ///POEG
    pub POEG: POEG,
    ///SRAM
    pub SRAM: SRAM,
    ///RTC
    pub RTC: RTC,
    ///SCI0
    pub SCI0: SCI0,
    ///SCI1
    pub SCI1: SCI1,
    ///SCI2
    pub SCI2: SCI2,
    ///SCI9
    pub SCI9: SCI9,
    ///SLCDC
    pub SLCDC: SLCDC,
    ///SPI0
    pub SPI0: SPI0,
    ///SPI1
    pub SPI1: SPI1,
    ///SSIE0
    pub SSIE0: SSIE0,
    ///TSN
    pub TSN: TSN,
    ///USBFS
    pub USBFS: USBFS,
    ///WDT
    pub WDT: WDT,
    ///ACMPLP
    pub ACMPLP: ACMPLP,
    ///ADC140
    pub ADC140: ADC140,
    ///AGT0
    pub AGT0: AGT0,
    ///AGT1
    pub AGT1: AGT1,
    ///GPT320
    pub GPT320: GPT320,
    ///GPT321
    pub GPT321: GPT321,
    ///GPT162
    pub GPT162: GPT162,
    ///GPT163
    pub GPT163: GPT163,
    ///GPT164
    pub GPT164: GPT164,
    ///GPT165
    pub GPT165: GPT165,
    ///GPT166
    pub GPT166: GPT166,
    ///GPT167
    pub GPT167: GPT167,
    ///GPT_OPS
    pub GPT_OPS: GPT_OPS,
}
impl Peripherals {
    /// Returns all the peripherals *once*.
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    /// Unchecked version of `Peripherals::take`.
    ///
    /// # Safety
    ///
    /// Each of the returned peripherals must be used at most once.
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            SYSTEM: SYSTEM::steal(),
            BUS: BUS::steal(),
            CAC: CAC::steal(),
            CAN0: CAN0::steal(),
            DBG: DBG::steal(),
            CRC: CRC::steal(),
            CTSU: CTSU::steal(),
            DAC12: DAC12::steal(),
            DAC8: DAC8::steal(),
            DMAC0: DMAC0::steal(),
            DMAC1: DMAC1::steal(),
            DMAC2: DMAC2::steal(),
            DMAC3: DMAC3::steal(),
            DMA: DMA::steal(),
            DOC: DOC::steal(),
            DTC: DTC::steal(),
            ELC: ELC::steal(),
            FCACHE: FCACHE::steal(),
            PORT0: PORT0::steal(),
            PORT1: PORT1::steal(),
            PORT2: PORT2::steal(),
            PORT3: PORT3::steal(),
            PORT4: PORT4::steal(),
            PORT5: PORT5::steal(),
            PORT6: PORT6::steal(),
            PORT7: PORT7::steal(),
            PORT8: PORT8::steal(),
            PORT9: PORT9::steal(),
            PFS: PFS::steal(),
            PMISC: PMISC::steal(),
            ICU: ICU::steal(),
            IIC0: IIC0::steal(),
            IIC1: IIC1::steal(),
            IWDT: IWDT::steal(),
            KINT: KINT::steal(),
            MSTP: MSTP::steal(),
            MMPU: MMPU::steal(),
            SMPU: SMPU::steal(),
            SPMON: SPMON::steal(),
            OPAMP: OPAMP::steal(),
            POEG: POEG::steal(),
            SRAM: SRAM::steal(),
            RTC: RTC::steal(),
            SCI0: SCI0::steal(),
            SCI1: SCI1::steal(),
            SCI2: SCI2::steal(),
            SCI9: SCI9::steal(),
            SLCDC: SLCDC::steal(),
            SPI0: SPI0::steal(),
            SPI1: SPI1::steal(),
            SSIE0: SSIE0::steal(),
            TSN: TSN::steal(),
            USBFS: USBFS::steal(),
            WDT: WDT::steal(),
            ACMPLP: ACMPLP::steal(),
            ADC140: ADC140::steal(),
            AGT0: AGT0::steal(),
            AGT1: AGT1::steal(),
            GPT320: GPT320::steal(),
            GPT321: GPT321::steal(),
            GPT162: GPT162::steal(),
            GPT163: GPT163::steal(),
            GPT164: GPT164::steal(),
            GPT165: GPT165::steal(),
            GPT166: GPT166::steal(),
            GPT167: GPT167::steal(),
            GPT_OPS: GPT_OPS::steal(),
        }
    }
}
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
#[cfg(all(feature = "fsp", feature = "cortex-m-rt-device"))]
compile_error!("Cannot enable both `fsp` and `cortex-m-rt-device` features at the same time.");
#[cfg(feature = "rt")]
impl Interrupt {
    pub const fn try_from_u16(n: u16) -> Option<Self> {
        assert!(__INTERRUPTS.len() < u16::MAX as usize);
        if n >= __INTERRUPTS.len() as u16 {
            return None;
        }
        Some(unsafe { ::core::mem::transmute(n as u16) })
    }
}
#[cfg(feature = "rt")]
#[derive(Debug)]
pub struct InvalidInterruptNumber;
#[cfg(feature = "rt")]
impl TryFrom<u16> for Interrupt {
    type Error = InvalidInterruptNumber;
    fn try_from(value: u16) -> Result<Self, Self::Error> {
        Interrupt::try_from_u16(value).ok_or(InvalidInterruptNumber)
    }
}
#[cfg(feature = "rt")]
impl core::error::Error for InvalidInterruptNumber {}
#[cfg(feature = "rt")]
impl core::fmt::Display for InvalidInterruptNumber {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "Invalid interrupt number")
    }
}
