[package]
name = "ra-fsp-rs"
version.workspace = true
edition = "2024"
description = "Rust HAL for Renesas RA microcontrollers using FSP (Flexible Software Package)"
authors = ["Oleksandr Babak <alexanderbabak@proton.me>"]
keywords = ["no-std", "embedded", "hal", "renesas", "fsp"]
categories = ["embedded", "hardware-support", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Ddystopia/ra"
readme = "README.md"

[dependencies]
ra-fsp-sys.workspace = true
cortex-m = { version = "0.7.7", default-features = false }
log = { version = "0.4.27", default-features = false, optional = true }
# todo: make pacs always require critical-section
ra6m3-pac = { workspace = true, optional = true, features = ["fsp", "critical-section"] }
ra4m1-pac = { workspace = true, optional = true, features = ["fsp", "critical-section"] }

smoltcp = { version = "0.12.0", default-features = false, optional = true }
critical-section = "1.2.0"
static_cell = "2.1.1"
rtic-monotonics = { version = "2.1.0", default-features = false, optional = true }
embassy-time-queue-utils = { version = "0.3.0", optional = true }
embassy-time-driver = { version = "0.2.1", optional = true }
pin-init = { git = "https://github.com/Rust-for-Linux/pin-init", version = "0.0.10", default-features = false }
# pin-init = { path = "/home/ddystopia/job/pin-init/impl_for_mut_ref", default-features = false }
# pin-init = { git = "https://github.com/Ddystopia/pin-init", version = "0.0.10", default-features = false, branch = "impl_for_mut_ref" }
atomic_refcell = "0.1.13"
atomic_once_cell = "0.2.0"

embedded-graphics = { version = "0.8.1", optional = true }
buoyant = { git = "https://github.com/riley-williams/buoyant", version = "0.7.0-alpha.0", optional = true, branch = "v0.7" }
diatomic-waker = { version = "0.2.3", default-features = false }
heapless = "0.9.1"

[features]
default = ["log", "device"]

device = ["ra-fsp-sys/device", "ra6m3-pac/rt"]

log = ["dep:log"]
smoltcp-ether = ["dep:smoltcp", "ra-fsp-sys/mod-r_ether", "smoltcp/medium-ethernet"]
rtic-monotonics = ["dep:rtic-monotonics"]
rtic-monotonics-gpt = ["mod-r_gpt", "rtic-monotonics"]
embassy-time-gpt = ["dep:embassy-time-queue-utils", "dep:embassy-time-driver", "mod-r_gpt"]
embedded-graphics-glcdc = ["dep:buoyant", "dep:embedded-graphics", "mod-r_glcdc"]

mod-r_dmac = ["ra-fsp-sys/mod-r_dmac"]
mod-r_elc = ["ra-fsp-sys/mod-r_elc"]

mod-r_flash_hp = ["ra-fsp-sys/mod-r_flash_hp"]

mod-r_icu = ["ra-fsp-sys/mod-r_icu"]
mod-r_ioport = ["ra-fsp-sys/mod-r_ioport"]
mod-r_gpt = ["ra-fsp-sys/mod-r_gpt", "mod-r_timer_api"]
mod-r_timer_api = ["ra-fsp-sys/mod-r_timer_api"]
mod-r_glcdc = ["ra-fsp-sys/mod-r_glcdc", "mod-r_display_api"]
mod-r_display_api = ["ra-fsp-sys/mod-r_display_api"]
mod-r_ether = ["ra-fsp-sys/mod-r_ether"]
mod-r_ether_phy = ["ra-fsp-sys/mod-r_ether_phy"]
mod-r_ether_phy_target_ics1894 = ["ra-fsp-sys/mod-r_ether_phy_target_ics1894"]
mod-r_ether_phy_target_ksz8091rnb = ["ra-fsp-sys/mod-r_ether_phy_target_ksz8091rnb"]
mod-r_ether_phy_target_ksz8041 = ["ra-fsp-sys/mod-r_ether_phy_target_ksz8041"]
mod-r_ether_phy_target_dp83620 = ["ra-fsp-sys/mod-r_ether_phy_target_dp83620"]

ra0e1 = []
ra2a1 = []
ra2a2 = []
ra2e1 = []
ra2e2 = []
ra2e3 = []
ra2l1 = []
ra4e1 = []
ra4e2 = []
ra4m1 = ["ra-fsp-sys/ra4m1", "dep:ra4m1-pac"]
ra4m2 = []
ra4m3 = []
ra4t1 = []
ra4w1 = []
ra6e1 = []
ra6e2 = []
ra6m1 = []
ra6m2 = []
ra6m3 = ["ra-fsp-sys/ra6m3", "dep:ra6m3-pac"]
ra6m4 = []
ra6m5 = []
ra6t1 = []
ra6t2 = []
ra6t3 = []
ra8m1 = []
ra8d1 = []
ra8t1 = []
