use core::{
    mem::{ManuallyDrop, zeroed},
    pin::Pin,
    ptr,
};

use ra_fsp_sys::generated::{
    self as api, self as raw, BSP_IRQ_DISABLED, GPT_CFG_OUTPUT_SUPPORT_ENABLE,
    GPT_CFG_PARAM_CHECKING_ENABLE, R_GPT_Close, R_GPT_Open, R_GPT0_Type, e_fsp_err, fsp_err_t,
    gpt_extended_cfg_t, gpt_instance_ctrl_t, timer_api_t, timer_callback_args_t, timer_cfg_t,
    timer_ctrl_t, timer_event_t, timer_instance_t,
};

const _: () = assert!(
    GPT_CFG_PARAM_CHECKING_ENABLE == 1,
    "The FSP configuration option GPT_CFG_PARAM_CHECKING_ENABLE is required with this crate, please enable it"
);

use crate::{
    Block, Callback, DriverBox, Result, TypeStateResult,
    callbacks::CallbackEvent,
    fsp_try_unsafe, pac,
    pin_init::{PinInit, pin_data, pin_init_from_closure, pinned_drop},
    state_markers::{Closed, Opened},
    timer_api::*,
    unsafe_pinned::UnsafePinned,
    utils,
};

pub use channel::*;

unsafe extern "C" {
    /// FSP's GPT ISR entries. Prefer [`Gpt::handle_isr`] /
    /// [`IsrPrototype::call_fsp_isr_handler`].
    ///
    /// # Safety
    ///
    /// Must run in the matching configured IRQ with the driver open. If a
    /// non-static callback that mutates the block is registered, the ISR must
    /// not preempt a driver call in progress — the callback would alias the
    /// suspended call's `&mut`. Driving it through [`Gpt::handle_isr`] from a
    /// context that owns the driver upholds both.
    pub unsafe fn gpt_counter_overflow_isr();
    /// See [`gpt_counter_overflow_isr`]'s safety contract.
    ///
    /// FSP compiles this symbol only for the triangle-wave PWM feature set
    /// (`GPT_CFG_OUTPUT_SUPPORT_ENABLE == 2`); guard every reference behind
    /// `UNDERFLOW_IRQ_ENABLED` (see [`IsrPrototype::call_fsp_isr_handler`]).
    pub unsafe fn gpt_counter_underflow_isr();
    /// See [`gpt_counter_overflow_isr`]'s safety contract.
    pub unsafe fn gpt_capture_compare_a_isr();
    /// See [`gpt_counter_overflow_isr`]'s safety contract.
    pub unsafe fn gpt_capture_compare_b_isr();
}

pub mod channel {
    /// A GPT channel peripheral.
    ///
    /// # Safety
    ///
    /// `Gpt<C, _>` is `Send`/`Sync` and hands out `&C` from a shared
    /// reference ([`Gpt::regs`]); implementations must tolerate that under
    /// the crate's single-core policy: `gtcnt()` must be callable from any
    /// context, and register access through `&Self` must not assume
    /// exclusivity.
    ///
    /// [`Gpt::regs`]: super::Gpt::regs
    pub unsafe trait Channel: Send {
        const N: usize;
        fn gtcnt() -> u32;
    }

    macro_rules! ch {
        ($periph: ident, $n: literal) => {
            // SAFETY: PAC peripherals are ZST handles; GTCNT is a plain
            // 32-bit read, valid from any context on a single core.
            unsafe impl Channel for $crate::pac::$periph {
                const N: usize = $n;
                fn gtcnt() -> u32 {
                    let gpt = unsafe { $crate::pac::$periph::steal() };
                    gpt.gtcnt().read().bits()
                }
            }
            unsafe impl Channel for &mut $crate::pac::$periph {
                const N: usize = $n;
                fn gtcnt() -> u32 {
                    let gpt = unsafe { $crate::pac::$periph::steal() };
                    gpt.gtcnt().read().bits()
                }
            }
        };
    }

    // The available GPT channels and their channel numbers depend on the MCU, so
    // the `ch!` invocations are generated by `build.rs`, which greps the active
    // PAC's generated `lib.rs` for its GPT channel peripherals.
    include!(concat!(env!("OUT_DIR"), "/gpt_channels.rs"));
}

const UNDERFLOW_IRQ_ENABLED: bool = GPT_CFG_OUTPUT_SUPPORT_ENABLE == 2;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord)]
pub enum IsrPrototype {
    #[default]
    Overflow,
    Underflow,
    CompareA,
    CompareB,
}

#[repr(C)] // `#[repr(C)]` is for typestate
#[pin_data(PinnedDrop)]
pub struct Gpt<'a, C, State: 'static> {
    user_data: *const (),
    cycle_end_irq: Option<pac::Interrupt>,
    capture_a_irq: Option<pac::Interrupt>,
    capture_b_irq: Option<pac::Interrupt>,
    c_ext_cfg: UnsafePinned<gpt_extended_cfg_t>,
    ctrl: UnsafePinned<gpt_instance_ctrl_t>,
    cfg: UnsafePinned<timer_cfg_t>,
    inst: UnsafePinned<timer_instance_t>,
    regs: C,
    _marker: core::marker::PhantomData<(State, &'a ())>,
}

#[derive(Default)]
pub struct GptExtendedConfig {
    pub gtioca: raw::gpt_output_pin_t,
    pub gtiocb: raw::gpt_output_pin_t,
    pub start_source: raw::gpt_source_t,
    pub stop_source: raw::gpt_source_t,
    pub clear_source: raw::gpt_source_t,
    pub capture_a_source: raw::gpt_source_t,
    pub capture_b_source: raw::gpt_source_t,

    pub count_up_source: raw::gpt_source_t,
    pub count_down_source: raw::gpt_source_t,
    pub capture_filter_gtioca: raw::gpt_capture_filter_t,
    pub capture_filter_gtiocb: raw::gpt_capture_filter_t,

    pub capture_a: Option<pac::Interrupt>,
    pub capture_b: Option<pac::Interrupt>,

    pub compare_match_value: [u32; 2],
    pub compare_match_status: u8,

    // `p_pwm_cfg` is not implemented
    // const * p_pwm_cfg: raw::gpt_extended_pwm_cfg_t,
    pub gtior_setting: raw::gpt_gtior_setting_t,
}

const API: timer_api_t = timer_api_t {
    open: Some(api::R_GPT_Open),
    stop: Some(api::R_GPT_Stop),
    start: Some(api::R_GPT_Start),
    reset: Some(api::R_GPT_Reset),
    enable: Some(api::R_GPT_Enable),
    disable: Some(api::R_GPT_Disable),
    periodSet: Some(api::R_GPT_PeriodSet),
    dutyCycleSet: Some(api::R_GPT_DutyCycleSet),
    compareMatchSet: Some(api::R_GPT_CompareMatchSet),
    infoGet: Some(api::R_GPT_InfoGet),
    statusGet: Some(api::R_GPT_StatusGet),
    callbackSet: Some(api::R_GPT_CallbackSet),
    close: Some(api::R_GPT_Close),
};

unsafe impl<C, S> crate::LifetimeDriver for Gpt<'static, C, S> {
    type Target<'a> = Gpt<'a, C, S>;
}

unsafe impl<C: Channel, S> Block for Gpt<'_, C, S> {
    type Config = timer_cfg_t;
    type Instance = timer_instance_t;
    type Api = timer_api_t;
    type State = S;

    const API: &'static Self::Api = &API;

    fn ctrl(&self) -> *mut core::ffi::c_void {
        UnsafePinned::raw_get(&raw const self.ctrl).cast()
    }

    fn instance(&self) -> &Self::Instance {
        unsafe { &*self.inst.get() }
    }
}

// The `Channel` bound is load-bearing: it is an unsafe trait whose contract
// makes sharing `&C` across contexts (via `regs`) defensible.
unsafe impl<C: Channel, S> Send for Gpt<'_, C, S> {}
unsafe impl<C: Channel, S> Sync for Gpt<'_, C, S> {}

impl IsrPrototype {
    /// Drive the matching FSP GPT ISR from an interrupt handler, after checking
    /// the interrupt vector points at it.
    ///
    /// Reads the active IRQ's [`pac::__INTERRUPTS`] slot and dispatches only if
    /// it holds the expected `gpt_*_isr` address, so it is safe to call from any
    /// context (a mismatch, or thread mode, is a no-op). This fits a
    /// direct-vector install where the FSP ISR sits directly in the vector
    /// table.
    ///
    /// Behind an indirected vector (e.g. an RTIC `#[task(binds = ..)]`
    /// dispatcher) the slot holds the trampoline, not the FSP ISR, so this
    /// no-ops; drive [`Gpt::handle_isr`] there, which gates on the active IRQ
    /// *number* instead of the vector contents.
    ///
    /// [`Gpt::handle_isr`]: crate::gpt::Gpt::handle_isr
    ///
    /// Requires the `device` feature, which brings in the PAC vector table this
    /// check reads.
    #[cfg(feature = "device")]
    pub fn call_fsp_isr_handler(self) {
        let Some(active) = utils::current_irq_get() else {
            return;
        };
        // `Vector` is `union { _handler: fn(), _reserved: u32 }` -- a single
        // word with the handler at offset 0, so reading the slot as `usize`
        // yields the installed handler address (Thumb bit set, matching
        // `f as *const () as usize`).
        let Some(ptr) = pac::__INTERRUPTS.get(active as usize) else {
            return;
        };
        let ptr_to_handler = core::ptr::from_ref(ptr).cast::<usize>();
        let target = match self {
            IsrPrototype::Overflow => gpt_counter_overflow_isr as *const () as usize,
            IsrPrototype::Underflow if UNDERFLOW_IRQ_ENABLED => {
                gpt_counter_underflow_isr as *const () as usize
            }
            IsrPrototype::Underflow => return,
            IsrPrototype::CompareA => gpt_capture_compare_a_isr as *const () as usize,
            IsrPrototype::CompareB => gpt_capture_compare_b_isr as *const () as usize,
        };
        if unsafe { *ptr_to_handler } == target {
            unsafe { self.call_fsp_isr_handler_unchecked() }
        }
    }

    /// Drive the matching FSP GPT ISR with no vector check.
    ///
    /// # Safety
    ///
    /// Call only from the channel's configured IRQ. This performs no vector
    /// check, so the caller owns the "correct IRQ" guarantee (e.g. a statically
    /// bound interrupt handler).
    #[inline(always)]
    pub unsafe fn call_fsp_isr_handler_unchecked(self) {
        unsafe {
            match self {
                IsrPrototype::Overflow => gpt_counter_overflow_isr(),
                IsrPrototype::Underflow => {
                    if UNDERFLOW_IRQ_ENABLED {
                        gpt_counter_underflow_isr()
                    }
                }
                IsrPrototype::CompareA => gpt_capture_compare_a_isr(),
                IsrPrototype::CompareB => gpt_capture_compare_b_isr(),
            }
        }
    }
}

unsafe impl<'a, C: Channel> CallbackEvent<timer_event_t> for Gpt<'a, C, Opened> {
    #[inline(always)]
    fn context(this: *mut Self) -> *mut *const Self {
        unsafe {
            let ctrl = UnsafePinned::raw_get(&raw const (*this).ctrl);
            let context = &raw mut (*ctrl).p_context;
            context.cast()
        }
    }

    #[inline(always)]
    fn process_args(args: *mut ()) -> (*mut Self, *const (), timer_event_t) {
        unsafe {
            let args = args.cast::<timer_callback_args_t>();

            let this = (*args).p_context.cast::<Self>().cast_mut();
            let event = (*args).event;
            if this.is_null() {
                (ptr::null_mut(), ptr::null(), event)
            } else {
                (this, (*this).user_data, event)
            }
        }
    }

    #[inline(always)]
    fn process_static_args(args: *mut ()) -> (*const (), timer_event_t) {
        unsafe {
            let args = args.cast::<timer_callback_args_t>();
            ((*args).p_context.cast::<()>(), (*args).event)
        }
    }

    #[inline(always)]
    fn user_data(this: *mut Self) -> *const () {
        unsafe { (*this).user_data }
    }

    #[inline(always)]
    fn fsp_callback_set<'b>(
        self: Pin<&'b mut Self>,
        p_callback: unsafe extern "C" fn(*mut ()),
        p_context: *const core::ffi::c_void,
        user_data: *const (),
    ) -> Result<()> {
        unsafe {
            let this = self.get_unchecked_mut();
            fsp_try_unsafe!(api::R_GPT_CallbackSet(
                this.ctrl.get().cast(),
                Some(Self::cast_callback(p_callback)),
                p_context,
                core::ptr::null_mut(),
            ))?;
            this.user_data = user_data;
            Ok(())
        }
    }
}

impl<'a, C: Channel> Gpt<'a, C, Opened> {
    pub fn new_open(
        gpt: C,
        cfg: TimerConf<GptExtendedConfig>,
    ) -> impl PinInit<Gpt<'a, C, Opened>, fsp_err_t> {
        unsafe {
            pin_init_from_closure(|slot: *mut Self| init_open::<C>(slot.cast::<Self>(), gpt, cfg))
        }
    }

    /// Drive a GPT ISR from its interrupt handler.
    ///
    /// No-ops unless the active IRQ is the channel's configured IRQ for
    /// `isr_prototype` (so thread mode or the wrong IRQ is harmless). The check
    /// is on the IRQ *number*, so it holds regardless of how the vector table is
    /// wired, including behind an RTIC `#[task(binds = ..)]` dispatcher.
    ///
    /// Pairs with a block-taking callback ([`callback_set`](Self::callback_set)):
    /// it hands `self` to the callback as the block, so the COMPARE_B callback
    /// reprograms the alarm through that block.
    #[inline(always)]
    pub fn handle_isr(self: Pin<&mut Self>, isr_prototype: IsrPrototype) {
        let expected_irq = match isr_prototype {
            IsrPrototype::Overflow | IsrPrototype::Underflow => self.cycle_end_irq,
            IsrPrototype::CompareA => self.capture_a_irq,
            IsrPrototype::CompareB => self.capture_b_irq,
        };
        let active = utils::current_irq_get();
        if expected_irq.is_none() || active != expected_irq {
            return;
        }
        CallbackEvent::with_callback_provenance(self, || unsafe {
            isr_prototype.call_fsp_isr_handler_unchecked()
        });
    }

    /// Registers a callback that receives the [`Gpt`] block when invoked. Drive
    /// it from the interrupt handlers with [`handle_isr`](Self::handle_isr),
    /// which passes the block in, so the callback need not borrow the driver
    /// from shared storage.
    ///
    /// May be non-static because invoking the callback requires some form of
    /// `&mut Self`.
    pub fn callback_set<F>(self: Pin<&mut Self>, context: &'a F) -> Result<()>
    where
        F: Callback<timer_event_t, Self> + Sync,
    {
        CallbackEvent::callback_set(self, context)
    }

    /// Registers a static callback that reaches its own state. Drive it with
    /// [`IsrPrototype::call_fsp_isr_handler`] or the raw `gpt_*_isr` externs.
    ///
    /// Must be `'static` because the `Gpt` may be closed/dropped during `F`'s
    /// call.
    pub fn callback_set_static<F>(self: Pin<&mut Self>, context: &'static F) -> Result<()>
    where
        F: Callback<timer_event_t> + Sync,
    {
        CallbackEvent::callback_set_static(self, context)
    }

    pub fn close<'any>(this: DriverBox<Self>) -> TypeStateResult<Gpt<'any, C, Closed>, Self> {
        if !this.is_open() {
            return Err((this, e_fsp_err::FSP_ERR_NOT_OPEN));
        }
        let mut this = ManuallyDrop::new(this);

        match fsp_try_unsafe!(R_GPT_Close(this.as_mut().ctrl().cast())) {
            Err(err) => Err((ManuallyDrop::into_inner(this), err)),
            Ok(_) => unsafe {
                let ptr = ptr::from_mut(this.get_unchecked_mut()).cast();
                Ok(DriverBox::new_unchecked(&mut *ptr))
            },
        }
    }
}

#[pinned_drop]
impl<C, S: 'static> PinnedDrop for Gpt<'_, C, S> {
    fn drop(mut self: Pin<&mut Self>) {
        // SAFETY: We can can close of course, and callbacks are fine too
        // - Non-static callback requires `Pin<&mut Self>`, thus this drop can't overlap.
        // - Static callback doesn't borrow from `self`
        if self.is_open() {
            if let Err(err) = fsp_try_unsafe!(R_GPT_Close(self.as_mut().ctrl_void())) {
                let channel = unsafe { (*self.cfg.get()).channel };
                log::error!("Failed to close GPT driver on channel {channel}: {err}");
            }
        }
    }
}

impl<'f, C: Channel> Gpt<'f, C, Closed> {
    pub const fn new(regs: C) -> Self {
        Self {
            user_data: ptr::null_mut(),
            regs,
            capture_a_irq: None,
            capture_b_irq: None,
            cycle_end_irq: None,
            c_ext_cfg: UnsafePinned::new(unsafe { zeroed() }),
            ctrl: UnsafePinned::new(unsafe { zeroed() }),
            cfg: UnsafePinned::new(unsafe { zeroed() }),
            inst: UnsafePinned::new(unsafe { zeroed() }),
            _marker: core::marker::PhantomData,
        }
    }
    pub fn open(
        this: DriverBox<Self>,
        cfg: TimerConf<GptExtendedConfig>,
    ) -> TypeStateResult<Gpt<'f, C, Opened>, Self> {
        if this.is_open() {
            return Err((this, e_fsp_err::FSP_ERR_ALREADY_OPEN));
        }

        unsafe {
            let mut this = ManuallyDrop::new(this);
            let p_this = ptr::from_mut(this.get_unchecked_mut());
            let regs = ptr::read(&(*p_this).regs);

            let p_this = p_this.cast::<Gpt<C, Opened>>();
            init_open(p_this, regs, cfg).map_err(|e| (ManuallyDrop::into_inner(this), e))?;
            Ok(DriverBox::new_unchecked(&mut *p_this))
        }
    }
}

unsafe fn init_open<C: Channel>(
    slot: *mut Gpt<'_, C, Opened>,
    gpt: C,
    mut cfg: TimerConf<GptExtendedConfig>,
) -> Result<()> {
    if cfg.channel as usize != C::N {
        log::error!("GPT: channel mismatch");
        return Err(e_fsp_err::FSP_ERR_ASSERTION);
    }

    unsafe {
        let this = Gpt {
            user_data: ptr::null(),
            cycle_end_irq: cfg.cycle_end,
            capture_a_irq: cfg.extend.capture_a,
            capture_b_irq: cfg.extend.capture_b,
            c_ext_cfg: zeroed(),
            ctrl: zeroed(),
            cfg: zeroed(),
            inst: zeroed(),
            regs: gpt,
            _marker: core::marker::PhantomData,
        };
        ptr::write(slot, this);

        (*(*slot).inst.get()).p_ctrl = (*slot).ctrl.get().cast::<core::ffi::c_void>();
        (*(*slot).inst.get()).p_cfg = (*slot).cfg.get().cast_const();
        (*(*slot).inst.get()).p_api = ptr::from_ref(&API);
        ptr::write((*slot).c_ext_cfg.get(), cfg.extend.c_conf());

        let p_ctrl = UnsafePinned::raw_get(&raw const (*slot).ctrl);
        let p_cfg = UnsafePinned::raw_get(&raw const (*slot).cfg);
        let p_extend = UnsafePinned::raw_get(&raw const (*slot).c_ext_cfg).cast();

        *p_cfg = cfg.c_conf();
        (*p_cfg).p_extend = p_extend;

        // FSP needs to IRQs to setup contexts, but it will additionally
        // unconditionally set priorities from cfg.
        // Thus we read them and give to FSP. FSP will thus not change them.
        // Critical section is for nothing to change priorities between out
        // read and FSP's write.
        critical_section::with(|_| {
            utils::try_read_priority_into(cfg.cycle_end, &mut (*p_cfg).cycle_end_ipl);

            let p_extend = (*p_cfg).p_extend.cast::<gpt_extended_cfg_t>().cast_mut();
            utils::try_read_priority_into(cfg.extend.capture_a, &mut (*p_extend).capture_a_ipl);
            utils::try_read_priority_into(cfg.extend.capture_b, &mut (*p_extend).capture_b_ipl);

            fsp_try_unsafe!(R_GPT_Open(p_ctrl.cast::<timer_ctrl_t>(), p_cfg))
        })
    }
}

impl<C, S> Gpt<'_, C, S> {
    pub fn is_open(&self) -> bool {
        unsafe { (*self.ctrl.get()).open != 0 }
    }

    #[inline(always)]
    fn ctrl_void(self: Pin<&mut Self>) -> *mut core::ffi::c_void {
        self.ctrl().cast()
    }

    #[inline(always)]
    fn ctrl(self: Pin<&mut Self>) -> *mut gpt_instance_ctrl_t {
        UnsafePinned::raw_get(&raw const self.ctrl)
    }

    pub fn cycle_end_irq(&self) -> Option<pac::Interrupt> {
        self.cycle_end_irq
    }
    pub fn capture_a_irq(&self) -> Option<pac::Interrupt> {
        self.capture_a_irq
    }
    pub fn capture_b_irq(&self) -> Option<pac::Interrupt> {
        self.capture_b_irq
    }

    #[inline(always)]
    pub const fn c_regs(&self) -> *mut R_GPT0_Type {
        unsafe { *self.ctrl.get() }.p_reg
    }

    #[inline(always)]
    pub const fn regs_ptr(&self) -> *mut pac::gpt328::RegisterBlock {
        unsafe { *self.ctrl.get() }.p_reg.cast()
    }

    // NOTE(soundness/policy): `Gpt` is unconditionally `Sync` (see the
    // `unsafe impl` above), and this hands out `&C` even though svd2rust
    // deliberately leaves peripherals `!Sync` — sharing it across priority
    // levels permits torn `modify()` read-modify-writes on registers. Not
    // Rust-AM UB on a single core (interrupts give happens-before), but it
    // bypasses the PAC's ownership discipline; multi-context users must
    // serialize register access themselves.
    #[inline(always)]
    pub const fn regs(&self) -> &C {
        &self.regs
    }
}

impl GptExtendedConfig {
    pub const fn c_conf(&self) -> gpt_extended_cfg_t {
        gpt_extended_cfg_t {
            gtioca: self.gtioca,
            gtiocb: self.gtiocb,
            start_source: self.start_source,
            stop_source: self.stop_source,
            clear_source: self.clear_source,
            capture_a_source: self.capture_a_source,
            capture_b_source: self.capture_b_source,
            count_up_source: self.count_up_source,
            count_down_source: self.count_down_source,
            capture_filter_gtioca: self.capture_filter_gtioca,
            capture_filter_gtiocb: self.capture_filter_gtiocb,
            capture_a_ipl: BSP_IRQ_DISABLED as u8,
            capture_b_ipl: BSP_IRQ_DISABLED as u8,
            capture_a_irq: utils::extract_irq(self.capture_a),
            capture_b_irq: utils::extract_irq(self.capture_b),
            compare_match_value: self.compare_match_value,
            compare_match_status: self.compare_match_status,
            p_pwm_cfg: ptr::null(),
            gtior_setting: self.gtior_setting,
        }
    }
}
